PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX spdx: <http://spdx.org/rdf/terms#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message (?s AS ?Subject) (?p AS ?Predicate) (?o AS ?Object)
WHERE{
GRAPH <@@@TOKEN-GRAPH@@@> {
# Rule_ID:0
  {SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a foaf:Agent.
     FILTER(!EXISTS {?s foaf:name ?name}).
     BIND (rdf:type AS ?p).
     BIND (foaf:Agent AS ?o).
     BIND ("Agent" AS ?Class_Name).
     BIND (0 AS ?Rule_ID).
     BIND ("error" AS ?Rule_Severity).
     BIND ("foaf:name is a required property for Agent." AS ?Rule_Description).
     BIND (concat("The agent  ",str(?o)," does not have a foaf:name property.") AS ?Message).
   }
  }

UNION
# Rule_ID:1
  {SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a foaf:Agent.
     ?s foaf:name ?o.
     FILTER(!isLiteral(?o)).
     BIND (foaf:name AS ?p)
     BIND ("Agent" AS ?Class_Name).
     BIND (1 AS ?Rule_ID).
     BIND ("error" AS ?Rule_Severity).
     BIND ("The foaf:name property should be a literal." AS ?Rule_Description).
     BIND (concat("The property ",str(?p)," is not a literal.") AS ?Message).
   }
  }

UNION
# Rule_ID:2
  {SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a foaf:Agent.
     FILTER(!EXISTS {?s dct:type ?type}).
     BIND (rdf:type AS ?p).
     BIND (foaf:Agent AS ?o).
     BIND ("Agent" AS ?Class_Name).
     BIND (2 AS ?Rule_ID).
     BIND ("warning" AS ?Rule_Severity).
     BIND ("dct:type is a recommended property for Agent." AS ?Rule_Description).
     BIND (concat("The foaf:Agent ",str(?o)," does not have a dct:type property.") AS ?Message).
   }
  }

UNION
# Rule_ID:3
  {SELECT DISTINCT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s (dct:type as ?p) ?o 
   WHERE {
     ?s a foaf:Agent.
     ?s dct:type ?o.
     ?o ?pred ?val.
     FILTER(!EXISTS {?o a skos:Concept}).
     BIND ("Agent" AS ?Class_Name).
     BIND (3 AS ?Rule_ID).
     BIND ("error" AS ?Rule_Severity).
     BIND ("dct:type should be a skos:Concept." AS ?Rule_Description).
     BIND (concat("foaf:Agent ",str(?s)," does not have a dct:type property of type skos:Concept.") AS ?Message).
   }
  }


}
}